### ISSUE TITLE
ブログ内容部分をSubmodule化する

### ISSUE THREAD

**Issue by miyaoka** [trkw/trkw#13]
ガンバッテ

**Comment by miyaoka** [comment]
# システムとコンテンツを分ける理由

ライセンスを分けたい。
システムの方は公開ライセンスで構わないが、コンテンツのほうは著作権的に転載など防止したい

**Comment by trkw** [comment]
`git submodule`にて、`content`ディレクトリを分けました。
`wercker.yml`にて、`git submodule`のコマンドを下記のように自動化します。


``` yaml
    - install-packages:
      packages: git
    - script:
      name: initialize git submodules
      code: |
        git submodule update --init --recursive
    - script:
      name: update git submodules
      code: |
        git submodule foreach git pull origin master
```

`git subtree`の方が、もしかしたら利用シーンにあっているかもしれないので、検討する。
